export const ActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
};
